services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - openstage_data:/app/database
      - openstage_shows:/app/shows

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    restart: always
    ports:
      - "8080:80"

volumes:
  openstage_data:
  openstage_shows: